version: 1.2.{build}
image: Visual Studio 2015
install:
- cmd: >-
    set QTDIR=C:\Qt\5.12.2\mingw73_32
    
    set PATH=%QTDIR%\bin;C:\cygwin;C:\cygwin64;C:\MinGW\bin;%PATH%;
    
build_script:
- cmd: >-
    qmake human_resource_machine.pro
    
    mingw32-make release
    
    mingw32-make clean
    
    cd release
    
    windeployqt human_resource_machine.exe
    
artifacts:
- path: release/
  name: human_resource_machine
  type: WebDeployPackage
  
deploy:
  provider: GitHub
  auth_token: bd1212de4c540be12822ba745a45622be2b61708
  description: 'HelloCI Release'
  draft: false
  prerelease: false
  on:
      APPVEYOR_REPO_TAG: true
